grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 2

model_selection:
  module_0:
    class: LinearRegression
    module: sklearn.linear_model
    param_grid:
      fit_intercept:
        - True
        - False
  module_1:
    class: RandomForestRegressor
    module: sklearn.ensemble
    param_grid:
      max_depth:
        - 5
        - 7
        - 10
      n_estimators:
        - 50
        - 100
        - 150
