grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 2

model_selection:
  model_0:
    class: LinearRegression
    module: sklearn.linear_model
    param_grid:
      fit_intercept:
        - True
        - False
  model_1:
    class: RandomForestRegressor
    module: sklearn.ensemble
    param_grid:
      max_depth:
        - 3
        - 5
      n_estimators:
        - 80
        - 100
